# This workflow will run build and publish to npm when version change

name: publish to npm

on:
  push:
      tags:
        - v*.*.*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      vitePath: ./dist/vite
      pluginPath: ./dist/webpack
      scriptPath: ./dist/script
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Harden Runner
        uses: arjundashrath/harden-runner@provge
        with:
          egress-policy: audit
      - run: yarn
      - run: yarn build
      - name: publish vite plugin
        run : npm publish
        working-directory: ${{env.vitePath}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish webpack plugin
        run : npm publish
        working-directory: ${{env.pluginPath}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish script plugin
        run : npm publish
        working-directory: ${{env.scriptPath}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}   
