# This workflow will run build and publish to npm when version change

name: publish to npm

on: [push, pull_request, workflow_dispatch]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      vitePath: ./dist/vite
      pluginPath: ./dist/webpack
      scriptPath: ./dist/script
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Harden Runner
        uses: arjundashrath/harden-runner@provgen
        with:
          egress-policy: audit
      - name: 'Upload Artifact'
      - run: npm publish
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: my_file.txt
          retention-days: 10
      - run: yarn
      - run: yarn build
      - name: publish vite plugin
        run : npm publish
        working-directory: ${{env.vitePath}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish webpack plugin
        run : npm publish
        working-directory: ${{env.pluginPath}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: publish script plugin
        run : npm publish
        working-directory: ${{env.scriptPath}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}   
